language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
before_install:
  - npm install -g npm@5.3.x
script:
  - npm test -- --coverage
  - npm run compile
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email:
    on_success: change
